### ISSUE TITLE
remove cohorts artifacts when discarding result

### ISSUE THREAD

**Issue by tkv29** [bptlab/TracEX#99] opened 2024-04-10 18:05 UTC
When users decide to discard the extraction results, the Cohort will still remain in the database, because it is always saved once extracted. This will affect all results, that have a relationship to the extracted Trace, right now Cohort is the only one implemented.

Possible solution from Frederic:
Change the execute_and_save() method to return a dictionary instead. Then the Orchestrator can handle saving the model instances all together – if the user wishes to do so. (Django can create model instances directly from dictionaries.).

Please consult @FR-SON when handling this task.

Small prompt adaption not related to the tasks above
- [ ] please adapt the prompt of the metrics analyzer that it also consider the cohort when evaluating the relevance category in the extraction pipeline

**Comment by PitButtchereit** [comment] 2024-04-18 11:17
Implementing this User Story should resolve the following issue described in #89 about the cohort being saved in the database: Since the cohort is saved to the database before the trace is extraced, there is no reference to the identifier of the trace. This results in the cohort name in the django admin view not referencing its respective trace. Currently the name is `extraction.Trace.None`.

Please check if the problem is solved when implementing this US.

**Comment by nils-schmitt** [comment] 2024-04-22 09:17
This can be resolved by moving the responsibility for saving results to the orchestrator. This way no module saves results to the db and the mentioned problem won't come up.

**Closed** 2024-05-17 12:19 UTC
Labels: High Prio, improvement
